# Generated by Django 6.0.3 on 2026-03-29 09:34

from django.db import migrations


def remove_username_column(apps, schema_editor):
    """Recreate accounts_user table without username column (SQLite workaround)."""
    cursor = schema_editor.connection.cursor()

    # Check if username column exists
    cursor.execute("PRAGMA table_info(accounts_user)")
    columns = [col[1] for col in cursor.fetchall()]
    if 'username' not in columns:
        return

    cursor.executescript("""
        CREATE TABLE accounts_user_new (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            password varchar(128) NOT NULL,
            last_login datetime,
            is_superuser bool NOT NULL,
            first_name varchar(150) NOT NULL,
            last_name varchar(150) NOT NULL,
            email varchar(254) NOT NULL UNIQUE,
            is_staff bool NOT NULL,
            is_active bool NOT NULL,
            date_joined datetime NOT NULL,
            role varchar(20) NOT NULL
        );

        INSERT INTO accounts_user_new
            (id, password, last_login, is_superuser, first_name, last_name,
             email, is_staff, is_active, date_joined, role)
        SELECT
            id, password, last_login, is_superuser, first_name, last_name,
            email, is_staff, is_active, date_joined, role
        FROM accounts_user;

        DROP TABLE accounts_user;
        ALTER TABLE accounts_user_new RENAME TO accounts_user;
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RunPython(remove_username_column, migrations.RunPython.noop),
    ]
