# Generated by Django 6.0.3 on 2026-03-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
